server:
  port: 8081

spring:
  application:
    name: SERVICE-HELLO

eureka:
  enabled: true
#  instance:
#  appname: eureka.client.01
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/